# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: abc
    ports:
      - "5432:5432"
    volumes:
        - "pgdata:/var/lib/postgresql/data"
volumes:
    pgdata:
