spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wcc
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: root
    baseline-description: "init"
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
